### PR TITLE
Support valid values for QRMatrixOption

### LINKED ISSUE #4: qrcode option_3 not allow mask
based on the documentation, you can use mask in option_3 in qrcode:

 QR Code has eight different masks designed to minimize unwanted patterns. The best mask to use is selected automatically by Zint but may be manually specified by using the --mask switch with values 0-7, or in the API by setting option_3 = (N + 1) << 8 where N is 0-7. To use with ZINT_FULL_MULTIBYTE set

option_3 = ZINT_FULL_MULTIBYTE | (N + 1) << 8

https://github.com/Enter-tainer/zint-wasi/blob/master/zint-wasm-rs/src/options/option3.rs#L55

But currently you can only use ZINT_FULL_MULTIBYTE. 
But it should be possible to use option_3 = (N + 1) << 8 and ZINT_FULL_MULTIBYTE | (N + 1) << 8

### PR DESCRIPTION
**Pull request by Caellian**
Fixes #4.

### CODE REVIEW

**Comment by Caellian** [comment]
@Enter-tainer can you check the settings to see why this PR can't be merged, [fix/qr-mask-opt3](https://github.com/Enter-tainer/zint-wasi/tree/fix/qr-mask-opt3) branch is based on `master`.

**Comment by Enter-tainer** [comment]
fixed

**Review by Enter-tainer — APPROVED** [review]

**Comment by lublak** [comment]
@Caellian thanks, currently not tested, because i need to build it first (im until monday away from my computer).
I have looked over the code and it should work for me for now. But I think there is one thing that is not supported: `ZINT_FULL_MULTIBYTE | (N + 1) << 8`
I don't currently use this option myself, only the masking option. But just for info.

**Comment by Caellian** [comment]
@lublak the check was ignoring bits set by `ZINT_FULL_MULTIBYTE`.

I've made it more explicit now.

**Comment by lublak** [comment]
> @lublak the check was ignoring bits set by `ZINT_FULL_MULTIBYTE`.
> 
> I've made it more explicit now.

Thanks! On the phone it's difficult to read. I will test it on Monday :)

**Comment by Enter-tainer** [comment]
i will publish a new version if it works for you. @lublak

**Comment by lublak** [comment]
@Enter-tainer @Caellian 

i know i know! Its not monday. But i had some time in the morning, so i tested it today! (i hope its okay xD)

Simply: it doesn't work.

```typ
tiaoma.qrcode(data, options: (
    option-1: 2, // M
    option-2: 2,
    option-3: (7 + 1).bit-lshift(8), // 2048
))
```

after a bit testing i found it, it goes here:
https://github.com/Enter-tainer/zint-wasi/blob/master/zint-wasm-rs/src/options/option3.rs#L32 which is not QR Options.

i simply swapped the code to test this

```
return Err(Error::UnknownOption {
                    which: "option_3_datamatrix",
                    value: Box::new(other),
                })
 return Err(Error::UnknownOption {
                        which: "option_3_qrmatrix",
                        value: Box::new(other),
                    });
eturn Err(Error::UnknownOption {
                    which: "option_3_ultracode",
                    value: Box::new(other),
                })
```

a bit more reading: https://github.com/Enter-tainer/zint-wasi/blob/master/zint-wasm-rs/src/options/option3.rs#L175

**Pull request merged**
