### PR TITLE
fix #4

### LINKED ISSUE #4: qrcode option_3 not allow mask
based on the documentation, you can use mask in option_3 in qrcode:

 QR Code has eight different masks designed to minimize unwanted patterns. The best mask to use is selected automatically by Zint but may be manually specified by using the --mask switch with values 0-7, or in the API by setting option_3 = (N + 1) << 8 where N is 0-7. To use with ZINT_FULL_MULTIBYTE set

option_3 = ZINT_FULL_MULTIBYTE | (N + 1) << 8

https://github.com/Enter-tainer/zint-wasi/blob/master/zint-wasm-rs/src/options/option3.rs#L55

But currently you can only use ZINT_FULL_MULTIBYTE. 
But it should be possible to use option_3 = (N + 1) << 8 and ZINT_FULL_MULTIBYTE | (N + 1) << 8

### PR DESCRIPTION
**Pull request by lublak**
additionally to: https://github.com/Enter-tainer/zint-wasi/pull/5

### CODE REVIEW

**Comment by Caellian** [comment]
I'll take a closer look tomorrow, but this change doesn't functionally change anything and just turns a match into a nested if.

Option3 needs to be touched up because it doesn't provide a good error message when no variants can be matched, so I'll do that as well soon.

**Comment by lublak** [comment]
@Caellian yes it doesn't change the logic. But somehow with your implementation the wasm doesn't work (I think it's a Compiler bug?)
After a lot of try and error, with a simple if else statement it works now (important here is the check the mask before the Full bytes).

**Comment by Enter-tainer** [comment]
Maybe this code triggers an undefined behavior? But unfortunately I don't know much about unsafe rust.

**Comment by Caellian** [comment]
Figured it out, the previous code didn't return transmuted value so it defaulted to the error message like it did before.

**Comment by Caellian** [comment]
Also, `saturating_sub` was a logic error.

I just refactored code into a match statement as it will look cleaner if additional options get added at some point.

<details>
<summary>Responses to open questions</summary>

> (I think it's a Compiler bug?)

Rust compiler generally doesn't have these sorts of bugs because it lowers into LLVM IR. Most compiler bugs cause compilation failure and not incorrect binary behavior. Also, given the age of the language, there's very few low hanging fruit (easy to reach) bugs on stable.

> Maybe this code triggers an undefined behavior? But unfortunately I don't know much about unsafe rust.

Transmute is like `reinterpret_cast` in C++ - to be valid source and target type must have same alignment or the source must be aligned to target alignment if its alignment is smaller; source must equal in size to target or larger (though that's a memory leak (which is safe/doesn't cause UB)). `#[repr(u32)]` on the enum makes is have the same layout as source `u32` and `#[non_exhaustive]` makes any code using the enum assume it's got some variants which aren't explicitly declared which forces all checks of the transmuted target value to be exhaustive. With those two annotations it's safe to transmute `u32` into marked enum; only `#[repr(u32)]` is required for transmuting the enum into `u32` (in reverse).

Sadly, unsafe rust is hard to get right even if you stare at the docs for a long time, and even then it _may_ break in later versions. This thing I used is a very common usage pattern though and isn't going away. I don't think I used any unsafe code that assumes too much in this library, but it _is required_ for C ffi.

</details>

Merging now, thanks for testing and debugging.

**Review by Caellian — APPROVED** [review]

**Comment by Enter-tainer** [comment]
Thank you! I will publish a new version when I leave work.

**Comment by lublak** [comment]
@Enter-tainer still at work? 😄

**Comment by Enter-tainer** [comment]
sorry! i forget this completely. i will do it tomorrow

**Comment by lublak** [comment]
@Enter-tainer all fine :) and thanks for the release!

**Pull request merged**
